### PR TITLE
Initial ranking - may need some help on the reate process

### PR DESCRIPTION
**Pull request by PaulMyhr**
@swm93 can you have a look? I havent added the button that will cause the system to perform the ranking and its untested. 

I believe in the create I will have to check if there is already a ranking for that application and term id and if there is, just update the score of it

### CODE REVIEW

**Comment by swm93** [comment]
Looks really good!

One thing though is that every time an application is created at least one new Ranking is created automatically as well. For example, if an application is created and it is for two terms (2015W, 2015F) then two rankings will automatically be created as well (one for each term).

Only other question I have is how you came up with the scale factor 0.046 for the GPA.

**Comment by PaulMyhr** [comment]
@swm93 

With your comment about it making rankings for each term? Is that what it should do or what it currently does? I wrote it assuming each ranking could only have 1 term - but may need to discuss.

Also, I believe I will have to add something like:

if (Ranking.find_by application_id: application.student_id, term_id: application.term_id) 
     then update that ranking instead with new score or don't do anything if same

only create a new one and save if it doesnt exist

**Comment by PaulMyhr** [comment]
Oh and the 0.046 for GPA was because I figured GPA could be out of a total 0.2 (out of the 1.0) and since GPA can be 4.33 as brett said - 0.046 \* 4.33 is max 0.2

**Comment by swm93** [comment]
We can definitely change it, but right now the schema is set up so that we have the following 3 tables:
Application(id, ...), Term(id, ...), Rank(application_id, term_id, ...)
There is a many-to-many relationship between Term and Application where Rank is the table that joins them. I thought it made sense to use Rank as the table that joins them so that if an Application was for multiple Terms (ie: 2015W, 2015F) then there could be a separate rank for each term.

**Pull request merged**
